<?
$aMenuLinks = Array(
    Array(
        "Возможности",
        "/opportunity/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Цены",
        "/price/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Решения",
        "/solution/",
        Array(),
        Array(),
        ""
    ),
);
?>